image: docker:latest

services:
  - docker:dind

before_script:
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
  - apk update && apk add bash

stages:
  - build

build-0.13:
  stage:  build
  script:
    - cd terraform0.13
    - bash ../build_script/docker.sh
  only:
    - tags

build-0.14:
  stage:  build
  script:
    - cd terraform0.14
    - bash ../build_script/docker.sh
  only:
    - tags

build-0.15:
  stage:  build
  script:
    - cd terraform0.15
    - bash ../build_script/docker.sh
  only:
    - tags

build-1.0:
  stage:  build
  script:
    - cd terraform1.0
    - bash ../build_script/docker.sh
  only:
    - tags
