image: docker:latest

services:
  - docker:dind

before_script:
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
  - apk update && apk add bash

stages:
  - build-0.13
  - build-0.14
  - build-0.15
  - build-1.0

build-0.13:
  stage:  build-0.13
  script:
    - cd terraform0.13
    - bash ../build_script/docker.sh

build-0.14:
  stage:  build-0.14
  script:
    - cd terraform0.14
    - bash ../build_script/docker.sh

build-0.15:
  stage:  build-0.15
  script:
    - cd terraform0.15
    - bash ../build_script/docker.sh

build-1.0:
  stage:  build-1.0
  script:
    - cd terraform1.0
    - bash ../build_script/docker.sh